[package]
name = "lfd"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1"
clap = { version = "4.3.8", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "test_bench"
harness = false

